spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: d05d4af2-3d66-44cf-9b3c-9fe6ac0a7c87
      config:
        server-addr: localhost:8848
        namespace: d05d4af2-3d66-44cf-9b3c-9fe6ac0a7c87
        file-extension: yaml
  config:
    import:
      - optional:nacos:ecommerce-common.yaml
      - optional:nacos:gateway.yaml
logging:
  level:
    org.springframework.cloud.gateway: TRACE
